'use strict';

const { BRIEF_ROWS, TICKERS, esc, playerLink, tickerLink, fmtPrice, fmtPct } = require('./db');

// ─────────────────────────────────────────────────────────────────────────────
// Entry point — returns the full HTML string for a brief issue
// ─────────────────────────────────────────────────────────────────────────────
function buildHtml(issue) {
  const { num, slug, date, title, deck, sports, markets, golf, trending, copy } = issue;
  const label = `#${String(num).padStart(3, '0')}`;
  const prevSlug = num > 1 ? `issue-${String(num - 1).padStart(3, '0')}` : null;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Brief · ${label} — GuyTalk</title>
<meta name="description" content="${esc(title)} — GuyTalk Issue ${label}.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@500;600;700;800;900&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/brief.css">
<!--
  Generated by: node scripts/generate-brief.js
  To create the next issue: run the same command tomorrow morning.
-->
</head>
<body>

<nav class="brief-nav">
  <div class="brief-nav-inner">
    <a href="/" class="brief-wordmark">GuyTalk<span class="dot">.</span></a>
    <div class="brief-nav-right">
      <span class="brief-nav-issue">The Brief · ${label}</span>
      <a href="/#signup" class="brief-cta">Subscribe free →</a>
    </div>
  </div>
</nav>

<article class="brief-article">

  <div class="brief-pretitle">
    <span class="brief-pretitle-dot"></span>
    ${esc(date)}
  </div>
  <h1 class="brief-title">${esc(title)}</h1>
  <p class="brief-deck">${esc(deck)}</p>
  <div class="brief-meta">
    <span>5 MIN READ</span>
    <span class="sep">·</span>
    <span>ISSUE ${label}</span>
    <span class="sep">·</span>
    <span>SPORTS · MARKETS · GOLF · CULTURE</span>
  </div>

${buildTldr(issue)}

${buildSports(issue)}

${buildMarkets(issue)}

${buildGolf(issue)}

${buildCulture(issue)}

${buildRec()}

${buildSharpTake(issue)}

${buildNumbers(issue)}

</article>

<footer class="brief-footer">
  <a href="/#signup" class="footer-cta">Get the brief free →</a>
  <p class="footer-meta">
    You're reading GuyTalk — the daily brief on sports, markets, golf, and culture.<br>
    Five minutes a day. Free forever. No algorithm.
  </p>
  <p class="footer-sig">— Jake, GuyTalk</p>
  <div class="footer-nav">
    <a href="/">Home</a>
    ${prevSlug ? `<a href="/brief/${prevSlug}/">Issue ${label.replace(String(num).padStart(3,'0'), String(num - 1).padStart(3,'0'))}</a>` : ''}
    <a href="mailto:guytalkdaily@gmail.com">Reply to Jake</a>
  </div>
</footer>

</body>
</html>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// TL;DR — auto-generated from data, falls back to REPLACE markers
// ─────────────────────────────────────────────────────────────────────────────
function buildTldr({ sports, markets, golf }) {
  const items = [];

  // Up to 2 sports bullets from game data
  (sports || []).slice(0, 2).forEach(g => {
    const w = g.home.winner ? g.home : g.away;
    const l = g.home.winner ? g.away : g.home;
    const note = g.note ? g.note.replace(/^NBA\s+/i, '') : g.shortName;
    items.push({
      tag: 'Sports', anchor: '#sports',
      html: `${esc(note)}: <strong>${esc(w.team)} ${esc(w.score)}</strong>, ${esc(l.team)} ${esc(l.score)}. <!-- REPLACE: Add player note (e.g. "Brunson 33 pts.") -->`,
    });
  });

  // Fill to 2 sports items if fewer than 2 games
  while (items.filter(i => i.tag === 'Sports').length < 2) {
    items.push({
      tag: 'Sports', anchor: '#sports',
      html: `REPLACE: Add sports headline. Format: "Series/matchup note. Player/stat. What's next."`,
    });
  }

  // Markets bullet — auto from Finnhub
  if (markets?.SPY?.dayChangePct !== null && markets?.SPY?.dayChangePct !== undefined) {
    const spy = markets.SPY;
    const dir = spy.dayChangePct >= 0 ? 'up' : 'down';
    items.push({
      tag: 'Markets', anchor: '#markets',
      html: `${tickerLink('SPY')} ${dir} ${fmtPct(spy.dayChangePct)} on the day. <!-- REPLACE: Add one key market note -->`,
    });
  } else {
    items.push({
      tag: 'Markets', anchor: '#markets',
      html: `REPLACE: Market headline. Format: "SPY/QQQ direction + %. Key story for next week."`,
    });
  }

  // Golf bullet — auto from ESPN data
  if (golf?.leaders?.[0]) {
    const l = golf.leaders[0];
    items.push({
      tag: 'Golf', anchor: '#golf',
      html: `${playerLink(l.name)} leads ${esc(golf.name)} at ${esc(l.score)}. <!-- REPLACE: Add context note -->`,
    });
  } else {
    items.push({
      tag: 'Golf', anchor: '#golf',
      html: `REPLACE: Golf headline. Format: "Player leads Tournament at score. What to watch."`,
    });
  }

  // Culture bullet — always manual
  items.push({
    tag: 'Culture', anchor: '#culture',
    html: `REPLACE: Culture headline. Format: "What happened. Why it matters." Max 20 words.`,
  });

  return `  <!-- TL;DR: Sports bullets auto-filled from ESPN data. Others need manual review. -->
  <div class="tldr">
    <div class="tldr-label">TL;DR — Five things to know</div>
    <ul class="tldr-list">
${items.slice(0, 5).map(item => `      <li class="tldr-item">
        <a href="${item.anchor}" class="tag-link"><span class="tag tag-amber">${item.tag}</span></a>
        <span>${item.html}</span>
      </li>`).join('\n')}
    </ul>
  </div>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Sports section — scoreboards + AI angle + REPLACE detail items
// ─────────────────────────────────────────────────────────────────────────────
function buildSports({ sports, copy }) {
  if (!sports?.length) {
    return `  <section class="brief-section" id="sports">
    <div class="section-label">Sports</div>
    <h3>REPLACE: Sports headline</h3>
    <!-- No game data found. Fill in scores and angles manually. -->
    <p>REPLACE: Add sports coverage. Scoreboard below can be filled in or removed.</p>
    <div class="scoreboard">
      <div class="score-side"><div class="score-team">TEAM A</div><div class="score-num">000</div></div>
      <div class="score-center"><div class="score-meta">REPLACE: Game label · Status</div><div class="score-badge">REPLACE Win</div></div>
      <div class="score-side right"><div class="score-team loser">TEAM B</div><div class="score-num loser">000</div></div>
    </div>
  </section>`;
  }

  const gameBlocks = sports.map((g, i) => {
    const w = g.home.winner ? g.home : g.away;
    const l = g.home.winner ? g.away : g.home;
    const homeLoser = !g.home.winner;
    const awayLoser = !g.away.winner;
    const metaText = g.note ? `${g.note} · ${g.status}` : g.status;
    const badge = `${esc(w.abbrev)} Win`;

    const scoreboard = `    <div class="scoreboard">
      <div class="score-side">
        <div class="score-team${homeLoser ? ' loser' : ''}">${esc(g.home.team)}</div>
        <div class="score-num${homeLoser ? ' loser' : ''}">${esc(g.home.score)}</div>
      </div>
      <div class="score-center">
        <div class="score-meta">${esc(metaText)}</div>
        <div class="score-badge">${badge}</div>
      </div>
      <div class="score-side right">
        <div class="score-team${awayLoser ? ' loser' : ''}">${esc(g.away.team)}</div>
        <div class="score-num${awayLoser ? ' loser' : ''}">${esc(g.away.score)}</div>
      </div>
    </div>`;

    // First game gets full treatment; subsequent get scoreboard + brief note
    if (i === 0) {
      const angleText = copy?.sportsAngle
        ? esc(copy.sportsAngle)
        : `REPLACE: Game analysis. Who was the key player? What was the turning point? What does this mean for the series?`;

      return `
    <h3>${esc(g.note || g.name)}</h3>

${scoreboard}

    <p>${angleText}</p>

    <ul class="detail-list">
      <li><span><span class="dl-label">REPLACE — key number:</span>REPLACE: The stat that defined this game. Format: "[Player] did X on Y." Make it specific.</span></li>
      <li><span><span class="dl-label">REPLACE — series situation:</span>REPLACE: Series record, next game date/time/venue. What this result means for momentum.</span></li>
      <li><span><span class="dl-label">How to watch:</span>REPLACE: "Game X · Day · Venue · Time ET · Network."</span></li>
    </ul>

    <div class="angle-box">
      <span class="angle-label">Group Chat Angle</span>
      <p class="angle-text">REPLACE: One specific, inside-knowledge fact about these two teams or players. Something your reader can drop once and sound like they actually know the game.</p>
    </div>`;
    }

    // Additional games: scoreboard + one-line note
    return `
    <h3>${esc(g.note || g.name)}</h3>

${scoreboard}

    <p>REPLACE: 2–3 sentences on this game. Key player, key moment, what's next.</p>`;
  });

  return `  <section class="brief-section" id="sports">
    <div class="section-label">Sports</div>
${gameBlocks.join('\n')}
  </section>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Markets section — ticker table auto-filled, narrative from AI or REPLACE
// ─────────────────────────────────────────────────────────────────────────────
function buildMarkets({ markets, copy, date }) {
  const openingPara = copy?.marketsTake
    ? `<p>${esc(copy.marketsTake)}</p>`
    : `<p>REPLACE: 2-sentence market take. What's the main story from today's session? What should readers watch next week?</p>`;

  const rows = BRIEF_ROWS.map(row => {
    if (row.type === 'divider') return '        <div class="mkt-div"></div>';

    const sym = row.key;
    const cfg = TICKERS[sym];
    const q = markets?.[sym];

    const price   = q?.price       ? fmtPrice(sym, q.price)       : '[PRICE]';
    const dayPct  = q?.dayChangePct !== undefined ? fmtPct(q.dayChangePct) : '[DAY%]';
    const dayDir  = q?.dayChangePct !== undefined ? (q.dayChangePct >= 0 ? 'up' : 'dn') : '';

    const nameHtml = cfg?.ms
      ? `<a href="https://www.morningstar.com/${cfg.ms}" class="ticker">${esc(cfg.display)}</a>`
      : esc(cfg?.display || sym);

    return `        <div class="mkt-row">
          <div class="m-name">${nameHtml}</div>
          <div class="m-val">${esc(price)}</div>
          <div class="m-day ${dayDir}">${esc(dayPct)}</div>
          <div class="m-wk">[WEEK%]</div><!-- Fill in weekly % manually -->
        </div>`;
  }).join('\n');

  return `  <!-- MARKETS: Prices auto-filled from Finnhub. Fill in [WEEK%] and [PRICE] manually where needed. -->
  <section class="brief-section" id="markets">
    <div class="section-label">Markets</div>

    <h3>REPLACE: Markets headline — one line that captures the week.</h3>

    ${openingPara}

    <p>REPLACE: Second paragraph — one thing that matters next week. Consumer confidence? Fed speak? Earnings? Thin volume?</p>

    <div class="mkt-table">
      <div class="mkt-table-hd">
        <div class="mkt-table-title">Daily Close</div>
        <div class="mkt-table-sub">${esc(date)}</div>
      </div>
      <div class="mkt-table-body">
        <div class="mkt-cols">
          <div class="th">Asset</div>
          <div class="th">Price</div>
          <div class="th">Day</div>
          <div class="th">Week</div>
        </div>
${rows}
      </div>
    </div>

    <ul class="detail-list">
      <li><span><span class="dl-label">Watch next week:</span>REPLACE: The one data point or event that will move markets. Be specific about date and what to expect.</span></li>
      <li><span><span class="dl-label">The one trade worth watching:</span>REPLACE: Pick one ticker showing unusual behavior. What's it doing, and why does it matter?</span></li>
      <li><span><span class="dl-label">What to bring up:</span>REPLACE: One portable market fact — something your reader can say at dinner. Specific number, true, useful.</span></li>
    </ul>
  </section>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Golf + Lifestyle — leaderboard auto-filled, product card is manual rotation
// ─────────────────────────────────────────────────────────────────────────────
function buildGolf({ golf, copy }) {
  let leaderboardHtml;

  if (golf?.leaders?.length) {
    const top5 = golf.leaders.slice(0, 5);
    const leaderName = top5[0].name;
    const leaderScore = top5[0].score;
    const leaderLineHtml = top5.map(p =>
      `${playerLink(p.name)} ${esc(p.score)} (${esc(p.pos)})`
    ).join(', ');

    leaderboardHtml = `
    <h3>${esc(golf.name)}: ${playerLink(leaderName)} leads at ${esc(leaderScore)}.</h3>

    <p><!-- AI golf note: ${esc(copy?.golfNote || 'Fill in a 2-sentence note on the leader and the tournament stakes.')} --></p>
    <p>REPLACE: Add your take on the tournament. Why does it matter? What's the storyline heading into the weekend?</p>

    <ul class="detail-list">
      <li><span><span class="dl-label">Leaderboard (${esc(golf.status || 'current')}):</span>${leaderLineHtml}. <!-- Verify at espn.com/golf before publishing --></span></li>
      <li><span><span class="dl-label">Why it matters:</span>REPLACE: What makes this tournament count — major points, field quality, historic venue, narrative.</span></li>
      <li><span><span class="dl-label">TV schedule:</span>REPLACE: "Saturday R3: TIME ET, NETWORK. Sunday R4: TIME ET, NETWORK."</span></li>
      <li><span><span class="dl-label">What to bring up:</span>REPLACE: One specific, inside-knowledge fact about the leader or this course. Not just a stat.</span></li>
    </ul>

    <div class="angle-box">
      <span class="angle-label">TV Schedule</span>
      <p class="angle-text">REPLACE: "Saturday Round 3: TIME ET, Golf Channel / Peacock. Sunday Round 4: TIME ET, NBC / Peacock."</p>
    </div>`;
  } else {
    leaderboardHtml = `
    <h3>REPLACE: Golf headline — tournament name + leader.</h3>
    <p>REPLACE: No active tournament data found. Add manually.</p>`;
  }

  return `  <section class="brief-section" id="golf">
    <div class="section-label">Golf + Lifestyle</div>
${leaderboardHtml}

    <!-- ── PRODUCT FEATURE ──────────────────────────────────────────────────
         Rotate this section each issue. Options: Peter Millar, Rhoback,
         TravisMathew, Holderness & Bourne, Footjoy, Titleist, etc.
         Image: ~400×533px portrait → /assets/images/FILENAME.jpg
    ────────────────────────────────────────────────────────────────────── -->
    <h3>The product worth knowing about.</h3>

    <div class="product-card">
      <div class="product-img">
        <!-- REPLACE: Add product image at /assets/images/PRODUCT-NAME.jpg -->
        <div class="product-img-ph">Add image:<br>/assets/images/<br>PRODUCT-NAME.jpg</div>
      </div>
      <div class="product-info">
        <div class="product-brand">REPLACE: Brand name</div>
        <div class="product-name">REPLACE: Product name</div>
        <p class="product-desc">REPLACE: 3–4 sentences. What it is, why it's worth knowing about, who it's for. One specific detail that earns the mention. Include a <a href="REPLACE_URL" class="brand">brand link</a>.</p>
        <span class="product-price">REPLACE: $000</span>
        <a href="REPLACE_URL" target="_blank" rel="noopener" class="product-link">Shop REPLACE →</a>
      </div>
    </div>

    <p style="font-size:14px; color:var(--text-3);">Other brands worth knowing: <a href="https://www.petermillar.com" class="brand">Peter Millar</a>, <a href="https://rhoback.com" class="brand">Rhoback</a>, <a href="https://www.travismathew.com" class="brand">TravisMathew</a>, <a href="https://holdernessandbourne.com" class="brand">Holderness &amp; Bourne</a>.</p>
  </section>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Culture — trending suggestions in comments, all items are manual
// ─────────────────────────────────────────────────────────────────────────────
function buildCulture({ trending }) {
  const suggestions = (trending || []).slice(0, 8)
    .map(t => `     ${esc(t.source)}: ${esc(t.title)} — ${esc(t.url)}`)
    .join('\n');

  const suggestionsBlock = suggestions
    ? `<!--
     TRENDING SUGGESTIONS (auto-fetched — pick what fits GuyTalk voice):
${suggestions}
  -->`
    : '<!-- No trending data. Check Reddit r/nba, r/golf, r/investing manually. -->';

  return `  <!-- CULTURE: All three items require manual curation. No auto-fill. -->
  ${suggestionsBlock}
  <section class="brief-section" id="culture">
    <div class="section-label">Culture</div>

    <ul class="culture-list">

      <!-- Culture item 1 — use a specific, named story. No vague "a CEO posted" lines. -->
      <li class="culture-item">
        <div>
          <div class="culture-head">REPLACE: Specific headline. Name the person, company, or moment.</div>
          <span class="culture-source">REPLACE: Platform · Source name · <a href="REPLACE_URL" target="_blank" rel="noopener">Link text</a></span>
          <p class="culture-body">REPLACE: 3–4 sentences. What happened exactly. Why people are reacting. What the correct take is — not "both sides," one right answer. End with one line the reader can use in conversation.</p>
        </div>
      </li>

      <!-- Culture item 2 — second story or follow-up -->
      <li class="culture-item">
        <div>
          <div class="culture-head">REPLACE: Second culture story. Be specific.</div>
          <span class="culture-source">REPLACE: Platform · Source name</span>
          <p class="culture-body">REPLACE: 3–4 sentences in GuyTalk voice. Same rules as above.</p>
        </div>
      </li>

      <!-- Culture item 3 — weekend entertainment rec -->
      <li class="culture-item">
        <div>
          <div class="culture-head">This weekend: REPLACE with actual movie, show, or event title.</div>
          <span class="culture-source">REPLACE: Netflix / HBO / Theater · Release date</span>
          <p class="culture-body">REPLACE: What it is, who made it, who it's for. One sentence on why it's worth your time. Don't oversell. "It's good, here's why" energy. Check <a href="https://www.rottentomatoes.com" target="_blank" rel="noopener">Rotten Tomatoes</a> for score before recommending.</p>
        </div>
      </li>

    </ul>
  </section>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// The Rec — rotate this weekly. Static template, manual swap.
// ─────────────────────────────────────────────────────────────────────────────
function buildRec() {
  return `  <!-- THE REC: Swap this each issue. App, gear, book, spot, service. One clean rec. -->
  <section class="brief-section" id="the-rec">
    <div class="section-label">The Rec</div>

    <div class="brief-rec">
      <div class="rec-label">This week's pick</div>
      <div class="rec-title">REPLACE: Item name — the one-line sell.</div>
      <p class="rec-body">REPLACE: 3–4 sentences. What it is. Why it's good. Who it's for. One specific detail that earns the mention (a feature, a fact, a price point). Don't mention it unless you'd actually recommend it.</p>
      <a href="REPLACE_URL" target="_blank" rel="noopener" class="rec-link">REPLACE: CTA text →</a>
    </div>
  </section>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Sharp Take — closing section, AI-drafted or REPLACE
// ─────────────────────────────────────────────────────────────────────────────
function buildSharpTake({ copy }) {
  const content = copy?.sharpTake
    ? copy.sharpTake.split('\n\n').map(p => `    <p>${esc(p.trim())}</p>`).join('\n')
    : `    <p>REPLACE: First paragraph. The big-picture read on this week. What the sports, markets, and culture stories have in common — or why the combination of them matters this specific weekend.</p>
    <p>REPLACE: Second paragraph. End with an action. "Clear Saturday. If someone asks you to do something else, the answer is no." Make it specific to this issue.</p>`;

  return `  <!-- SHARP TAKE: ${copy?.sharpTake ? 'AI-drafted — review before publishing.' : 'Needs manual copy.'} -->
  <div class="sharp-take">
    <div class="sharp-take-label">The Sharp Take</div>
${content}
  </div>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Numbers worth stealing — auto-generated where possible, else REPLACE
// ─────────────────────────────────────────────────────────────────────────────
function buildNumbers({ sports, markets, golf }) {
  const items = [];

  // From sports: series record
  if (sports?.length) {
    const g = sports[0];
    const note = g.note || g.shortName;
    items.push({
      num: `${g.home.score}–${g.away.score}`,
      html: `<strong>${esc(note)}.</strong> REPLACE: What this score means in context. What's the stat or historical fact that makes it significant?`,
    });
  }

  // From markets: SPY move
  if (markets?.SPY?.dayChangePct !== undefined && markets.SPY.dayChangePct !== null) {
    const pct = Math.abs(markets.SPY.dayChangePct).toFixed(1);
    const dir = markets.SPY.dayChangePct >= 0 ? 'gain' : 'drop';
    items.push({
      num: `${markets.SPY.dayChangePct >= 0 ? '+' : ''}${markets.SPY.dayChangePct.toFixed(1)}%`,
      html: `<strong>S&amp;P 500 ${dir} today.</strong> REPLACE: What does this number mean in context? Is it bullish? A rebound? Volume situation?`,
    });
  }

  // Golf stat
  if (golf?.leaders?.[0]) {
    items.push({
      num: golf.leaders[0].score,
      html: `<strong>${esc(golf.leaders[0].name)} leading ${esc(golf.name)}.</strong> REPLACE: One fact that makes this leaderboard interesting. Historic performance? Course record pace? Significance for FedEx Cup standings?`,
    });
  }

  // Pad to 3 items
  while (items.length < 3) {
    items.push({
      num: 'REPLACE',
      html: `<strong>REPLACE: Bold context sentence.</strong> REPLACE: 2 sentences explaining why this number matters and what to do with it.`,
    });
  }

  return `  <div class="brief-section">
    <div class="section-label">Numbers worth stealing</div>
    <ul class="numbers-list">
${items.slice(0, 3).map(item => `      <li class="numbers-item">
        <div class="n-num">${esc(item.num)}</div>
        <div>${item.html}</div>
      </li>`).join('\n')}
    </ul>
  </div>`;
}

module.exports = { buildHtml };
